### ISSUE TITLE
Link in README is inaccessible

### ISSUE THREAD

**Issue by rohilsaraf97** [Layr-Labs/cerberus-api#2]
The link referenced in the README file appears to be inaccessible. It points to a section within the codebase that cannot be accessed as intended.

> If you are implementing a version of this, please make sure to check [this code](https://github.com/Layr-Labs/remote-bls/blob/55a19a0386edcee1b5c2ecae116ae468a6b2b47b/internal/crypto/utils.go#L30-L36) for implementation of sign and verify. If you use any other implementation, the signatures will not be compatible with EigenLayer contracts. Eventually we will support more HashToCurve algorithms.

**Comment by shrimalmadhur** [comment]
ah interesting -thanks for noticing @rohilsaraf97 - I will update
